language: node_js
node_js:
  - '12'
addons:
  chrome: stable
branches:
  - develop
  - /^release-[0-999].[0-999]$/
  - /^issue#([1-9]|[1-8][0-9]|9[0-9]|[1-8][0-9]{2}|9[0-8][0-9]|99[0-9]|1000)$/
  - master
notifications:
  email:
    recipients:
      - alberto95.rm@gmail.com
script:
  - ng e2e --protractor-config=e2e/protractor-travis.conf.js
  - npm run test
  - npm run server-test

# Deploy https://betca-tpv-angular.herokuapp.com #TODO
#deploy:
  #provider: heroku
  #api_key:
    #secure: $HEROKU
  #on:
    #branch: master
