language: node_js
node_js:
  - '12'
addons:
  chrome: stable
  sonarcloud:
    organization: "albertogarciag95-github"
branches:
  - develop
  - /^release-[0-999].[0-999]$/
  - /^issue#([1-9]|[1-8][0-9]|9[0-9]|[1-8][0-9]{2}|9[0-8][0-9]|99[0-9]|1000)$/
  - master
notifications:
  email:
    recipients:
      - alberto95.rm@gmail.com
install:
  - npm install
script:
  - npm run lint
  - ng e2e --port 4201 --protractor-config=e2e/protractor-travis.conf.js
  - ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run server-test
  - sonar-scanner -Dsonar.projectKey=ToDoToday -Dsonar.sources=src1

# Deploy https://betca-tpv-angular.herokuapp.com #TODO
#deploy:
  #provider: heroku
  #api_key:
    #secure: $HEROKU
  #on:
    #branch: master
