language: node_js
node_js:
  - '12'
addons:
  chrome: stable
branches:
  - develop
  - /^release-[0-999].[0-999]$/
  - /^issue#([1-9]|[1-8][0-9]|9[0-9]|[1-8][0-9]{2}|9[0-8][0-9]|99[0-9]|1000)$/
  - master
cache:
  directories:
     - ./node_modules
notifications:
  email:
    recipients:
      - alberto95.rm@gmail.com
install:
  - npm install
script:
  - npm run lint
  - ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run server-test


# Deploy https://betca-tpv-angular.herokuapp.com #TODO
#deploy:
  #provider: heroku
  #api_key:
    #secure: $HEROKU
  #on:
    #branch: master
